language: python
sudo: false
deploy:
  provider: pypi
  user: arokem
  password:
    secure: AcCbZHWGp1aX5VBik35fpJTdnrWkmipH/PdaE+g7uwxq0//HQoIrL/k7Cs1u9rMn4C7xQlPJsz76kpepmuvM3dPFEiTZTfdL7ZT421gb4hQq/yMP/8XyuRrY8AqoRzOQ77JEYSFxTyVOgmrsEWnIim8gdUlYcn0qlwgWdijQjY4=
  on:
    tags: true
    repo: nipy/nitime
python:
- 2.7
- 3.3
- 3.4
- 3.5
env:
- CONDA_DEPS="pip nose coverage numpy scipy matplotlib networkx" PIP_DEPS="coveralls
  nibabel"
before_install:
- export MINICONDA=$HOME/miniconda
- export PATH="$MINICONDA/bin:$PATH"
- hash -r
- command -v conda >/dev/null || { wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh
  -O miniconda.sh; bash miniconda.sh -b -f -p $MINICONDA; }
- conda config --set always_yes yes
- conda update conda
- conda info -a
- conda install python=$TRAVIS_PYTHON_VERSION $CONDA_DEPS
- travis_retry pip install $PIP_DEPS
install:
- python setup.py install --record installed_files.txt
script:
- nosetests -v --with-coverage --cover-package=nitime
after_success:
- coveralls
before_cache:
- conda clean -tp
- xargs rm <installed_files.txt
cache:
  directories:
  - $HOME/miniconda
